name: jolly_pairs
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # utopia libs
  utopia_arch: ^0.4.0
  utopia_hooks: ^0.3.1
  utopia_widgets: ^0.0.9+2
  utopia_utils: ^0.2.11

  # architecture
  provider: ^6.0.1
  injector: ^2.0.0
  fast_immutable_collections: ^7.2.1

  # firebase
  firebase_core: ^2.4.1

  # platform APIs

  # misc widgets
  flutter_svg: ^2.0.0+1

  # misc utils
  intl: ^0.18.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lint
  utopia_lints: ^0.0.1+1

dependency_overrides:
  intl: ^0.18.0

flutter:
  fonts:
    - family: Salsa
      fonts:
        - asset: fonts/Salsa-Regular.ttf
